name: Build and Release

on:
  workflow_dispatch: 
    
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v8
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build for Linux
        run: dotnet publish -c Release -r linux-x64 --self-contained

      - name: Build for Windows
        run: dotnet publish -c Release -r win-x64 --self-contained

      - name: Build for macOS
        run: dotnet publish -c Release -r osx-x64 --self-contained

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload Linux release
        uses: actions/upload-artifact@v2
        with:
          name: linux-release
          path: bin/Release/net8.0/linux-x64/publish

      - name: Upload Windows release
        uses: actions/upload-artifact@v2
        with:
          name: windows-release
          path: bin/Release/net8.0/win-x64/publish

      - name: Upload macOS release
        uses: actions/upload-artifact@v2
        with:
          name: macos-release
          path: bin/Release/net8.0/osx-x64/publish
